### ISSUE TITLE
'int' object is not iterable

### ISSUE THREAD

**Issue by alduxvm** [omwah/pixy_rpi#2] opened 2015-06-27 14:05 UTC
Hi!

I'm getting this output when testing the echo.py:

```
python echo.py 
Traceback (most recent call last):
  File "echo.py", line 6, in <module>
    num_blocks = p.getBlocks()
  File "/home/pi/pixy_rpi/pixy.py", line 42, in getBlocks
    if not self._getStart():
  File "/home/pi/pixy_rpi/pixy.py", line 74, in _getStart
    w = self.link.getWord()
  File "/home/pi/pixy_rpi/pixy_spi.py", line 49, in getWord
    w = self.getByte(PIXY_SYNC_BYTE)
  File "/home/pi/pixy_rpi/pixy_spi.py", line 63, in getByte
    _, c = wiringpi2.wiringPiSPIDataRW(0, struct.pack('B', out))
TypeError: 'int' object is not iterable
```

I used pip to install wiringpi2 (sudo pip install wiringpi2) and I enabled the spi via raspi-config. 

Any ideas?

**Comment by omwah** [comment] 2015-06-27 16:31
I think the wiringpi2 interface changed recently. Try changing the line in pixy_spi.py that is causing the exception to this:

     c = wiringpi2.wiringPiSPIDataRW(0, struct.pack('B', out))

**Comment by alduxvm** [comment] 2015-06-27 16:53
ok, changing getByte function to:
```
    def getByte(self, out=0x00):
        """ return uint8_t """
        # Using file handles doesn't work too well
        #os.write(self.fd, struct.pack('B', out))
        #c = os.read(self.fd, 1)
        # Requires a fixed version of wiringpi2 SPI function
        c = wiringpi2.wiringPiSPIDataRW(0, struct.pack('B', out))
        ret = struct.unpack('B', c)[0]
        return ret
```

and then testing again:

```
~/pixy_rpi $ python echo.py 
Traceback (most recent call last):
  File "echo.py", line 6, in <module>
    num_blocks = p.getBlocks()
  File "/home/pi/pixy_rpi/pixy.py", line 42, in getBlocks
    if not self._getStart():
  File "/home/pi/pixy_rpi/pixy.py", line 74, in _getStart
    w = self.link.getWord()
  File "/home/pi/pixy_rpi/pixy_spi.py", line 49, in getWord
    w = self.getByte(PIXY_SYNC_BYTE)
  File "/home/pi/pixy_rpi/pixy_spi.py", line 64, in getByte
    ret = struct.unpack('B', c)[0]
struct.error: unpack requires a string argument of length 1
```

:S

**Comment by omwah** [comment] 2015-06-27 17:28
Okay. Now I remember. I had to modify wiringpi2-Python to return the actual value for the wiringPiSPIDataRW routine: https://github.com/omwah/WiringPi2-Python/commit/abf2d0ecb95ce30a6c7981eb6103d3d022d459df

That was merged into their archive, but I think the change got lost when they updated their SWIG inputs to a new version of the C wiringpi2 library.

You could just try and revert the change you made to pixy_spi.py and use my copy of [WiringPi2-Python](https://github.com/omwah/WiringPi2-Python). Or you could make the similar fix I made into the standard [WiringPi2-Python repo](https://github.com/Gadgetoid/WiringPi2-Python) and eventually send them a merge request to include that fix.

**Comment by omwah** [comment] 2015-06-27 17:30
Actually I take that back. Their version does still have my fix. I think the problem is whatever you pulled using pip is outdated. You should install from their git repo instead.

**Comment by alduxvm** [comment] 2015-06-28 10:24
Ok, I deleted everything, uninstalled the pip version, and followed your instructions for installing WiringPi2-Python from (https://github.com/omwah/WiringPi2-Python)

And I'm back to: 
```
TypeError: 'int' object is not iterable
```

I checked the cables of the rpi and I updated the pixy firmware, is there a way to know if the pixy is working via SPI? or if my SPI is working on the rpi? I removed from the black-list and I have them on the /dev... spidev0.0 spidev0.1

**Comment by omwah** [comment] 2015-07-06 05:54
The problem is something to do with the updates to wiringPi2-Python in the master repo. For now use my repository to install wiringPi2-Python if pixy_spi is all you need it for. I tried merging from their upstream repo but had some issues compiling that I haven't had time to figure out yet.

**Comment by omwah** [comment] 2015-07-10 03:04
I have put a fix into my repo of [WiringPi2-Python](https://github.com/omwah/WiringPi2-Python). I ahev also issued a [pull request](https://github.com/Gadgetoid/WiringPi2-Python/pull/30) to the main repo. Use my repo or wait for Gadgetoid to merge the pull request.

**Closed as completed by omwah** 2015-07-10 03:04 UTC
